;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Health",DevComment="")
+GameplayTagList=(Tag="Data.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Magic.Equip",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger",DevComment="")
+GameplayTagList=(Tag="Event.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="Gameplay.Active",DevComment="")
+GameplayTagList=(Tag="Gameplay.AOEAttack",DevComment="")
+GameplayTagList=(Tag="Gameplay.AOEAttack.HealingShower",DevComment="")
+GameplayTagList=(Tag="Gameplay.Attack.Active",DevComment="")
+GameplayTagList=(Tag="Gameplay.Attack.Combo",DevComment="")
+GameplayTagList=(Tag="Gameplay.Attack.SwordSwing",DevComment="")
+GameplayTagList=(Tag="Gameplay.Death",DevComment="")
+GameplayTagList=(Tag="Gameplay.EquipWEapon",DevComment="")
+GameplayTagList=(Tag="Gameplay.HitReaction",DevComment="")
+GameplayTagList=(Tag="Gameplay.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOEIndicator",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HealingShower",DevComment="")
+GameplayTagList=(Tag="Magic.AOEAttack.HealingShower",DevComment="")
+GameplayTagList=(Tag="Magic.Projectile.Fireball",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Weapon.Magic.Staff",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Sword",DevComment="")

